version: 2

project_name: dirnote

builds:
  - binary: dirnote
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
      - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: naosuke884
    name: dirnote

brews:
  - name: dirnote
    directory: Formula
    repository:
      owner: naosuke884
      name: dirnote
