version: 2

project_name: dirnote

builds:
  - binary: dirnote
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
  - format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: naosuke884
    name: dirnote

brews:
  - name: dirnote
    # リポジトリ内の Formula 配置先ディレクトリ
    directory: Formula
    # Homebrew Tap としてコミットする先リポジトリ情報
    repository:
      owner: naosuke884
      name: dirnote
