version: 2

project_name: dirnote

builds:
  - binary: dirnote
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  # tar.gz 用アーカイブ
  - id: tar
    formats:
      - tar.gz
  # zip 用アーカイブ
  - id: zip
    formats:
      - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: naosuke884
    name: dirnote

brews:
  - name: dirnote
    directory: Formula
    repository:
      owner: naosuke884
      name: dirnote
    # Homebrew では tar アーカイブのみ使う
    ids:
      - tar
